---
- name: "Test Minions"
  hosts: all

  vars:
    git_dir: "/home/{{ ansible_user_id }}/git/minions"
    config_file: "~/.config/xfce4/panel/whiskermenu-8.rc"
    display: ":0.0"
    default_theme: "Greybird"
    default_icon_theme: "elementary-xfce-dark"
  tasks:
    - name: get code
      git:
        dest: "{{ git_dir }}"
        repo: 'https://github.com/ochosi/minions.git'
      when: deactivate is not defined
    - name: compile
      shell: ./autogen.sh && make
      args:
        chdir: "{{git_dir}}"
      when: deactivate is not defined
    - name: install
      become: true
      shell: "make -C {{git_dir}} install"
      when: deactivate is not defined
    - name: Set whiskermenu to Minion
      lineinfile:
        path: "{{config_file}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=start-here'
      when: deactivate is not defined
    - name: Set whiskermenu to default
      lineinfile:
        path: "{{config_file}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=xubuntu-logo-menu'
      when: deactivate is defined

    - name: Set Minion theme
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "Minions"
      when: deactivate is not defined
    - name: Set default theme
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "{{default_theme}}"
      when: deactivate is defined

    - name: Set Minion theme
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "Minions"
      when: deactivate is not defined
    - name: Set default theme
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "{{default_icon_theme}}"
      when: deactivate is defined

    - name: activate
      shell: xfce4-panel -r
      environment:
        DISPLAY: "{{display}}"
