---
- name: "Test Minions"
  hosts: localhost

  vars:
    config_file: "~/.config/xfce4/panel/whiskermenu-*.rc"
    display: ":0.0"
    default_theme: "Greybird"
    default_icon_theme: "elementary-xfce-dark"
    default_cursor_theme: "Default"
    local_changes_bool: "{{local_changes|default(false)|bool}}"
    deactivate_bool: "{{deactivate|default(false)|bool}}"
    activate: "{{not deactivate_bool}}"
  pre_tasks:
    - name: Verify Ansible version requirements.
      assert:
        that: "ansible_version.full | version_compare('2.4', '>=')"
        msg: >
          "You must update Ansible to at least 2.4 to use this playbook."
  tasks:
    - name: install dependencies
      become: true
      apt:
        name: ruby-sass,build-essential,libgdk-pixbuf2.0-dev,libxml2-utils,automake
    - name: compile
      when: activate
      shell: ./autogen.sh && make
    - name: install
      when: activate
      become: true
      shell: "make install"

    - name: Find whiskermenu configfile
      find:
        paths: "{{ config_file }}"
      register: config_files
    - name: Set whiskermenu to Minion
      when: activate
      lineinfile:
        path: "{{item.path}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=start-here'
      with_items: "{{ config_files.files }}"
    - name: Set whiskermenu to default
      when: not activate
      lineinfile:
        path: "{{item.path}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=xubuntu-logo-menu'
      with_items: "{{ config_files.files }}"

    - name: Set Minion theme
      when: activate
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "Minions"
    - name: Set default theme
      when: not activate
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "{{default_theme}}"

    - name: Set Minion theme
      when: activate
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "Minions"
    - name: Set default icons
      when: not activate
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "{{default_icon_theme}}"

    - name: Set Unicorn Cursor
      when: activate
      shell: xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "Unicorn"
    - name: Set default Cursors
      when: not activate
      shell: xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "{{default_cursor_theme}}"

    - name: activate
      shell: xfce4-panel -r
      environment:
        DISPLAY: "{{display}}"
