---
- name: "Test Minions"
  hosts: all

  vars:
    git_dir: "/home/{{ ansible_user_id }}/git/minions"
    config_file: "~/.config/xfce4/panel/whiskermenu-8.rc"
    display: ":0.0"
    default_theme: "Greybird"
    default_icon_theme: "elementary-xfce-dark"
    default_cursor_theme: "Default"
    local_changes_bool: "{{local_changes|default(false)|bool}}"
    deactivate_bool: "{{deactivate|default(false)|bool}}"
    activate: "{{not deactivate_bool}}"
  tasks:
    - name: get code
      git:
        dest: "{{ git_dir }}"
        repo: 'https://github.com/ochosi/minions.git'
      when: activate and not local_changes_bool
    - name: compile
      shell: ./autogen.sh && make
      args:
        chdir: "{{git_dir}}"
      when: activate
    - name: install
      become: true
      shell: "make -C {{git_dir}} install"
      when: activate
    - name: Set whiskermenu to Minion
      lineinfile:
        path: "{{config_file}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=start-here'
      when: activate
    - name: Set whiskermenu to default
      lineinfile:
        path: "{{config_file}}"
        regexp: '^button-icon=.*$'
        line: 'button-icon=xubuntu-logo-menu'
      when: not activate

    - name: Set Minion theme
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "Minions"
      when: activate
    - name: Set default theme
      shell: xfconf-query -c xsettings -p /Net/ThemeName -s "{{default_theme}}"
      when: not activate

    - name: Set Minion theme
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "Minions"
      when: activate
    - name: Set default icons
      shell: xfconf-query -c xsettings -p /Net/IconThemeName -s "{{default_icon_theme}}"
      when: not activate

    - name: Set Unicorn Cursor
      shell: xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "Unicorn"
      when: activate
    - name: Set default Cursors
      shell: xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "{{default_cursor_theme}}"
      when: not activate

    - name: activate
      shell: xfce4-panel -r
      environment:
        DISPLAY: "{{display}}"
